package:
  name: openjpeg
  version: 2.1.1

source:
    url: https://github.com/uclouvain/openjpeg/archive/v2.1.1.tar.gz
    fn: v2.1.1.tar.gz

build:
  number: 0

requirements:
  build:
    - cmake
    - python
    - libpng
    - libtiff
  run:
    - python
