package:
    name: python-xmp-toolkit
    version: 2.0.1

source:
  fn: h5py-2.4.0.tar.gz                                                  [unix]
  url: https://pypi.python.org/packages/source/p/python-xmp-toolkit/python-xmp-toolkit-2.0.1.tar.gz  [unix]
  md5: 5836cb9bc252d06517ba262b3fb5a579                                  [unix]

requirements:
  build:
    - exempi         [unix]
    - setuptools
    - pytz         
  run:
    - python
    - exempi         [unix]
    - pytz         

about:
    home: https://python-xmp-toolkit.readthedocs.org/en/latest/
    license: New BSD (http://opensource.org/licenses/bsd-license.php)
