package:
  name: exempi
  version: 2.3.0

source:
  fn: exempi-2.3.0.tar.bz2
  url: https://libopenraw.freedesktop.org/download/exempi-2.3.0.tar.bz2

build:
  number: 0

requirements:
  build:
    - expat
    - boost
  run:
    - expat
    - boost

about:
  home: https://libopenraw.freedesktop.org/wiki/Exempi/
  license: New-BSD

# vim:set ts=8 sw=2 sts=2 tw=78 et:
